title: Painfully Extracted Creativity
author: Maurice Elliott
baseurl: "/"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: MauriceElliott
# Build settings
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

favicon: "logo.png"

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
